[tool.poetry]
name = "traffic-emissions"
version = "0.1.0"
description = "This indicator computes carbon dioxide emissions from road traffic in an area of interest within Germany"
authors = ["Veit Ulrich <veit.ulrich@heigit.org>, Sebastian Block <sebastian.block@heigit.org>, Emily Wilke <emily.wilke@heigit.org>"]
readme = "README.md"
repository = "https://gitlab.heigit.org/climate-action/plugins/traffic-emissions"

[tool.poetry.dependencies]
python = ">=3.11.5,<3.12"
climatoology = { git = "ssh://git@gitlab.heigit.org:2022/climate-action/climatoology.git", tag = "6.4.3" }
pydantic = ">=2.8.2,<3.0.0"
ohsome = "^0.4.0"
matplotlib = "^3.10.5"
earthengine-api = "^1.6.9"
geemap = "^0.36.3"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-cov = "^6.1.1"
vcrpy = {version = "^7.0.0", markers = "platform_python_implementation !='PyPy'"}
approvaltests = "^15.2.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pytest = "^8.4.1"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules
select = [
    # defaults
    "F",
    "E4", "E7", "E9",
    # additional
    "A", # be sure not to shadow built-in functions
    "I", # isort to sort imports
    "N", # check for use of PEP8 naming conventions
    # docstring cleaning
    "D201", "D207", "D208", "D209", "D210", "D214", "D215", "D300", "D403",
    # auto-remove unused 'noqa' comments
    "RUF100", "RUF101",
]

[tool.coverage.run]
omit = ["test/*", "traffic_emissions/core/*"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"