[tool.poetry]
name = "plugin-blueprint"
version = "0.0.1"
description = "This is a blueprint for Climate Action plugins. It serves as a basis for new plugins and by default creates a minimal working plugin example."
authors = ["Moritz Schott <moritz.schott@heigit.org>", "Danielle Gatland <danielle.gatland@heigit.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11.5"
climatoology = { git = "ssh://git@gitlab.heigit.org:2022/climate-action/climatoology.git", tag = "6.2.0" }
pydantic = "^2.8.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"

[tool.ruff]
line-length = 120

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules
select=[
    # defaults
    "F",
    "E4", "E7", "E9",

    # additional
    "A", # be sure not to shadow built-in functions
    "I", # isort to sort imports
    "N", # check for use of PEP8 naming conventions

    # docstring cleaning
    "D201", "D207", "D208", "D209", "D210", "D214", "D215", "D300", "D403",

    # auto-remove unused 'noqa' comments
    "RUF100", "RUF101",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
